version: '3.9'

services:
  cron:
    image: pexcn/docker-images:cron
    container_name: cron
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
      CRONTAB: |-
        10 10 * * * /srv/hifini.sh
    volumes:
      - ./cron-data:/srv
