version: '3.9'

services:
  transproxy:
    image: pexcn/docker-images:transproxy
    container_name: transproxy
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DISABLE_IPV6: 0
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./transproxy-data:/etc/transproxy
