version: '3.9'

services:
  dev-isolate:
    image: pexcn/docker-images:dev-isolate
    container_name: dev-isolate
    restart: unless-stopped
    network_mode: host
    environment:
      ENABLE_SSHD: 1
      SSH_PORT: 2222
      DOCKER_GID: 972
      USERNAME: user
      PASSWORD: password
      ROOT_PASSWORD: password
      GIT_USER: username
      GIT_EMAIL: mail@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data:/data
