version: '3.9'

services:
  ssserver:
    image: pexcn/docker-images:shadowsocks-rust
    container_name: ssserver
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
      CHILLING_EFFECT: 0
      SHADOWSOCKS_PASSWORD_1: password_1
      SHADOWSOCKS_PASSWORD_2: password_2
      SHADOWSOCKS_PASSWORD_3: password_3
    volumes:
      - ./shadowsocks-rust-data:/etc/shadowsocks-rust
      - ../../utils/acme.sh/acme.sh-data/example.com_ecc:/.acme.sh/example.com
    command: ssservice server --user nobody --config /etc/shadowsocks-rust/server.json

  sslocal:
    image: pexcn/docker-images:shadowsocks-rust
    container_name: sslocal
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
      CHILLING_EFFECT: 0
      SHADOWSOCKS_PASSWORD_1: password_1
      SHADOWSOCKS_PASSWORD_2: password_2
      SHADOWSOCKS_PASSWORD_3: password_3
    volumes:
      - ./shadowsocks-rust-data:/etc/shadowsocks-rust
    command: ssservice local --user nobody --config /etc/shadowsocks-rust/local.json
