version: '3.9'

services:
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    restart: unless-stopped
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: --bind_ip 127.0.0.1
