version: '3.9'

services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      #- ./nginx-data/root:/srv/root
      - ../acme.sh/acme.sh-data:/cert
      - /etc/localtime:/etc/localtime:ro
