version: '3.9'

services:
  rust:
    image: pexcn/docker-images:rust
    container_name: rust
    restart: unless-stopped
    network_mode: host
    environment:
      GIT_USER: username
      GIT_EMAIL: mail@example.com
      #ENABLE_SSH_DAEMON: 0
      #SSH_PORT: 2222
    volumes:
      - rust-data:/vscode
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /etc/ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
    #command: echo "Hello Rust!"

volumes:
  rust-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/rust-data
