version: '3.9'

services:
  phantun:
    image: pexcn/docker-images:phantun
    container_name: phantun
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Taipei
      RUST_LOG: INFO
    command: >
      phantun-server --local 1985 --remote 127.0.0.1:1984 --ipv4-only
