services:
  phantun-server:
    image: pexcn/docker-images:phantun
    container_name: phantun-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    #depends_on:
    #  - phantun-server-0
    logging:
      options:
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      USE_IPTABLES_NFT_BACKEND: 0
      RUST_LOG: INFO
    command: >
      phantun-server --local 1985 --remote 127.0.0.1:1985 --ipv4-only
        --tun phantun-server --tun-local 10.10.100.1 --tun-peer 10.10.100.2

  phantun-client:
    image: pexcn/docker-images:phantun
    container_name: phantun-client
    restart: unless-stopped
    network_mode: host
    privileged: true
    #depends_on:
    #  - phantun-client-0
    logging:
      options:
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      USE_IPTABLES_NFT_BACKEND: 0
      RUST_LOG: INFO
    command: >
      phantun-client --local 127.0.0.1:1985 --remote 11.22.33.44:1985 --ipv4-only
        --tun phantun-client --tun-local 10.10.100.1 --tun-peer 10.10.100.2
