services:
  android:
    image: pexcn/docker-images:android
    container_name: android
    restart: unless-stopped
    network_mode: host
    environment:
      GIT_USER: username
      GIT_EMAIL: mail@example.com
      ENABLE_SSHD: 1
      SSH_PORT: 7777
    volumes:
      - android-data:/vscode
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /etc/ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro

volumes:
  android-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/android-data
