version: '3.9'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11-debian
    container_name: uptime-kuma
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
      UPTIME_KUMA_HOST: 127.0.0.1
      UPTIME_KUMA_PORT: 3002
    volumes:
      - ./uptime-kuma-data:/app/data
      #- /var/run/docker.sock:/var/run/docker.sock
