version: '3.9'

services:
  chinadns-ng:
    image: pexcn/docker-images:chinadns-ng
    container_name: chinadns-ng
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    command: >
      -b 0.0.0.0
      -l 5353
      -c 223.5.5.5
      -t 127.0.0.1#5300
      -g /etc/chinadns-ng/gfwlist.txt
      -m /etc/chinadns-ng/chinalist.txt
      -o 3
      -p 3
      -f
      -r
