version: '3.9'

services:
  home-assistant:
    image: homeassistant/home-assistant:2022.7
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./home-assistant-data:/config
