services:
  trojan-server:
    image: pexcn/docker-images:trojan
    container_name: trojan-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./server.json:/etc/trojan/config.json
      - ../acme.sh/acme.sh/example.com_ecc/fullchain.cer:/etc/trojan/fullchain.cer
      - ../acme.sh/acme.sh/example.com_ecc/example.com.key:/etc/trojan/private.key
      - /etc/localtime:/etc/localtime:ro
