services:
  mtg:
    image: pexcn/docker-images:mtg
    container_name: mtg
    restart: unless-stopped
    network_mode: host
    command: >
      simple-run 0.0.0.0:990 7kgi5pN2PoUloLUu4FPEVDJ3d3cuYmluZy5jb20
      --prefer-ip=prefer-ipv4
      --doh-ip=8.8.8.8
