version: '3.9'

services:
  mtg:
    image: pexcn/docker-images:mtg
    container_name: mtg
    restart: unless-stopped
    network_mode: host
    environment:
      BIND_TO: 0.0.0.0:990
      SECRET: 7kgi5pN2PoUloLUu4FPEVDJ3d3cuYmluZy5jb20
      TCP_BUFFER: 512kb
