version: '3.9'

services:
  kcptun-libev-server:
    image: pexcn/docker-images:kcptun-libev
    container_name: kcptun-libev-server
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./kcptun-libev-data:/etc/kcptun-libev
    command: -c /etc/kcptun-libev/server.json

  kcptun-libev-client:
    image: pexcn/docker-images:kcptun-libev
    container_name: kcptun-libev-client
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./kcptun-libev-data:/etc/kcptun-libev
    command: -c /etc/kcptun-libev/client.json
