services:
  smartdns-china:
    image: pexcn/docker-images:smartdns
    container_name: smartdns-china
    restart: unless-stopped
    network_mode: host
    logging:
      options:
        max-size: 20m
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./smartdns-data/smartdns-china.conf:/etc/smartdns/smartdns.conf
      - ./smartdns-data/smartdns-china.cache:/etc/smartdns/smartdns.cache

  smartdns-world:
    image: pexcn/docker-images:smartdns
    container_name: smartdns-world
    restart: unless-stopped
    network_mode: host
    logging:
      options:
        max-size: 20m
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./smartdns-data/smartdns-world.conf:/etc/smartdns/smartdns.conf
      - ./smartdns-data/smartdns-world.cache:/etc/smartdns/smartdns.cache
