version: '3.9'

services:
  strongswan:
    image: pexcn/docker-images:strongswan
    container_name: strongswan
    restart: unless-stopped
    network_mode: bridge
    privileged: true
    environment:
      PSK: "PreSharedKey"
      USERS: "user1:password1,user2:password2"
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
