services:
  pcap2socks:
    image: pexcn/docker-images:pcap2socks
    container_name: pcap2socks
    restart: unless-stopped
    network_mode: host
    command: >
      --interface eth0
      --source 192.168.1.50
      --publish 192.168.1.11
      --destination 127.0.0.1:1080
