services:
  nezha-dashboard:
    image: pexcn/docker-images:nezha
    container_name: nezha-dashboard
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./nezha-data:/opt/nezha
    command: dashboard -c /opt/nezha/dashboard.yml -db /opt/nezha/dashboard.db

  nezha-agent:
    image: pexcn/docker-images:nezha
    container_name: nezha-agent
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      TZ: Asia/Taipei
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - ./nezha-data:/opt/nezha
    command: agent -c /opt/nezha/agent.yml
