version: '3.9'

services:
  gogs:
    image: gogs/gogs:0.12.3
    container_name: gogs
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: <git uid>
      PGID: <git gid>
    volumes:
      - ./gogs-data:/data
      #- ../acme.sh/acme.sh-data:/cert
      - /etc/localtime:/etc/localtime:ro
