version: '3.9'

services:
  gogs:
    image: gogs/gogs:0.12.9
    container_name: gogs
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: <git uid>
      PGID: <git gid>
      TZ: Asia/Taipei
    volumes:
      - ./gogs-data:/data
      - /path/to/git-repos:/data/git/repos
