version: '3.9'

services:
  cc:
    image: pexcn/docker-images:c
    container_name: cc
    restart: unless-stopped
    network_mode: host
    environment:
      GIT_USER: username
      GIT_EMAIL: mail@example.com
      ENABLE_SSHD: 1
      SSH_PORT: 3333
    volumes:
      - cc-data:/vscode
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /etc/ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro

volumes:
  cc-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/cc-data
