services:
  webdav:
    image: pexcn/docker-images:webdav
    container_name: webdav
    restart: unless-stopped
    network_mode: host
    environment:
      UID: 1000
      GID: 1000
    volumes:
      - ./webdav-data/config.yml:/etc/webdav/config.yml
      - /mnt/data:/data
      - /etc/localtime:/etc/localtime:ro
