version: '3.9'

services:
  nginx:
    image: pexcn/docker-images:nginx
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_NICE
    logging:
      options:
        max-file: 5
        max-size: 20m
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - ./nginx-data/http.d:/etc/nginx/http.d
      - ./nginx-data/stream.d:/etc/nginx/stream.d
      - ./nginx-data/html:/usr/share/nginx/html
      - ../../utils/acme.sh/acme.sh-data:/cert
    labels:
      - "me.pexcn.container.name=nginx"
    command: nginx-quic -g 'daemon off;'
