services:
  vohive:
    image: pexcn/docker-images:vohive
    container_name: vohive
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Taipei
    #dns:
    #  - 194.25.0.52
    #  - 194.25.0.60
    #  - 194.25.0.68
    volumes:
      - ./vohive-data/config:/opt/vohive/config
      - ./vohive-data/data:/opt/vohive/data
      - ./vohive-data/logs:/opt/vohive/logs
