services:
  vohive:
    image: pexcn/docker-images:vohive
    container_name: vohive
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Taipei
    devices:
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/cdc-wdm0:/dev/cdc-wdm0
    volumes:
      - ./vohive-data/config:/opt/vohive/config
      - ./vohive-data/data:/opt/vohive/data
      - ./vohive-data/logs:/opt/vohive/logs
