services:
  vohive:
    image: pexcn/docker-images:vohive
    container_name: vohive
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Asia/Taipei
    #extra_hosts:
    #  - "epdg.epc.mnc002.mcc262.pub.3gppnetwork.org=139.7.117.168"
    #  - "epdg.epc.mnc002.mcc262.pub.3gppnetwork.org=139.7.117.169"
    #  - "epdg.epc.mnc002.mcc262.pub.3gppnetwork.org=139.7.117.170"
    volumes:
      - ./vohive-data/config:/opt/vohive/config
      - ./vohive-data/data:/opt/vohive/data
      #- ./vohive-data/logs:/opt/vohive/logs
