services:
  shell:
    image: pexcn/docker-images:shell
    container_name: shell
    restart: unless-stopped
    network_mode: host
    environment:
      GIT_USER: username
      GIT_EMAIL: mail@example.com
      ENABLE_SSHD: 1
      SSH_PORT: 2222
    volumes:
      - shell-data:/vscode
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /etc/ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro

volumes:
  shell-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shell-data
