version: '3.9'

services:
  wireguard:
    image: pexcn/docker-images:wireguard
    container_name: wireguard
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      USE_USERSPACE_MODE: 0
      PEER_RESOLVE_INTERVAL: 0
    volumes:
      - ./wireguard-data:/etc/wireguard
