version: '3.9'

services:
  adguardhome:
    image: adguard/adguardhome:v0.106.3
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./adguardhome-data/conf:/opt/adguardhome/conf
      - ./adguardhome-data/work:/opt/adguardhome/work
