version: '3.9'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.8
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./adguardhome-data/conf:/opt/adguardhome/conf
      - ./adguardhome-data/work:/opt/adguardhome/work
