version: '3.9'

services:
  frps:
    image: pexcn/docker-images:frp
    container_name: frps
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: >
      frps --bind_addr 127.0.0.1 --bind_port 7000 --kcp_bind_port 7000

  frpc:
    image: pexcn/docker-images:frp
    container_name: frpc
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: >
      frpc tcp --server_addr 127.0.0.1:7000 --proxy_name ssserver --protocol tcp --uc --local_ip 127.0.0.1 --local_port 2077 --remote_port 2077
