version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:1.25.0-alpine
    container_name: vaultwarden
    restart: unless-stopped
    network_mode: host
    user: nobody
    env_file: ./config.env
    environment:
      ROCKET_ENV: production
    volumes:
      - ./vaultwarden-data:/data
      - /etc/localtime:/etc/localtime:ro
