version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:1.23.1-alpine
    container_name: vaultwarden
    restart: unless-stopped
    network_mode: host
    env_file: ./config.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./vaultwarden-data:/data
