version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:1.23.1-alpine
    container_name: vaultwarden
    restart: unless-stopped
    network_mode: host
    user: nobody
    environment:
      ROCKET_ENV: production
    volumes:
      - ./vaultwarden-data/config.env:/.env
      - ./vaultwarden-data:/data
      - /etc/localtime:/etc/localtime:ro
