services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14-openssl
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto-data/config:/mosquitto/config
      - ./mosquitto-data/data:/mosquitto/data
      - ./mosquitto-data/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
