version: '3.9'

services:
  acme.sh:
    image: neilpang/acme.sh:3.0.1
    container_name: acme.sh
    restart: unless-stopped
    network_mode: host
    environment:
      HE_Username: user
      HE_Password: pass
    volumes:
      - ./acme.sh-data:/acme.sh
      - /etc/localtime:/etc/localtime:ro
    command: daemon
