version: '3.9'

services:
  motd:
    image: pexcn/docker-images:motd
    container_name: motd
    restart: unless-stopped
    network_mode: bridge
    environment:
      TZ: Asia/Taipei
      MESSAGE_HEADER: "\nWelcome to ARCH!\n"
    volumes:
      - /etc/motd:/etc/motd
      - /var/log/lastlog:/var/log/lastlog:ro
