version: '3.9'

services:
  caddy:
    image: caddy:2.4.6
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy-data/Caddyfile:/etc/caddy/Caddyfile
      - ../acme.sh/acme.sh-data:/cert
      - /etc/localtime:/etc/localtime:ro
