name: Build

on:
  push:
    paths-ignore:
      - '_deprecated/**'
      - 'ext/**'
      - '**.md'
      - '**/docker-compose.yml'
      - '*'
  workflow_dispatch:
    inputs:
      global:
        description: 'Whether to build globally'
        required: false
        type: boolean
        default: false

env:
  TZ: Asia/Taipei

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix_json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changes
        id: detect-changes
        uses: tj-actions/changed-files@v47
        with:
          files_ignore: |
            _deprecated/**
            ext/**
            **.md
            **/docker-compose.yml
            *
          dir_names: true
          dir_names_max_depth: 2
          matrix: true

      - name: Create matrix
        id: create-matrix
        run: |
          changed_files='${{ steps.detect-changes.outputs.all_changed_files }}'
          global_build=${{ github.event.inputs.global == 'true' }}

          # override as global build
          if jq -e 'any(startswith(".github/"))' <<< "$changed_files" >/dev/null \
            || [ "$global_build" = true ]; then
            changed_files=$(
              # find build context dirs
              find . -mindepth 2 -maxdepth 2 -type d ! -path './.*' -prune -printf '%P\n' |
                # convert to json array
                jq -Rs 'split("\n")[:-1]' |
                # remove unused dirs
                jq '[.[] | select(startswith("_deprecated/") or startswith("ext/") | not)]'
            )
          fi

          matrix_json=$(jq -c -n --argjson ctxs "$changed_files" '
            {
              include: [
                $ctxs[] | . as $ctx | {
                  BUILD_CONTEXT: $ctx,
                  BUILD_TAG: ($ctx | split("/") | .[-1]),
                  TARGET_PLATFORMS: (
                    if (
                      [
                        "buildbot/bookworm",
                        "buildbot/bookworm-android",
                        "buildbot/bookworm-openwrt"
                      ] | index($ctx)
                    ) != null
                    then
                      "linux/amd64"
                    else
                      "linux/amd64,linux/arm64"
                    end
                  )
                }
              ]
            }
          ')
          echo "matrix_json=$matrix_json" >> $GITHUB_OUTPUT

      - name: Show matrix
        run: echo '${{ steps.create-matrix.outputs.matrix_json }}' | jq

  build-and-push:
    name: Build image
    needs: generate-matrix
    concurrency:
      group: ${{ matrix.BUILD_CONTEXT }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    uses: pexcn/github-builder/.github/workflows/build.yml@main
    permissions:
      contents: read
      packages: write
    with:
      output: image
      push: ${{ github.event_name == 'push' }}
      context: ${{ matrix.BUILD_CONTEXT }}
      platforms: ${{ matrix.TARGET_PLATFORMS }}
      cache: true
      cache-scope: ${{ matrix.BUILD_TAG }}
      meta-images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      meta-tags: |
        type=raw,value=${{ matrix.BUILD_TAG }}
      sign: false
      ssh: default
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  clean-untagged:
    if: always()
    needs: build-and-push
    runs-on: ubuntu-24.04
    steps:
      - name: Cleanup untagged images
        # use actions/delete-package-versions instead?
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
