name: DockerHub

on:
  push:
    branches: master
  workflow_dispatch:

env:
  TZ: Asia/Taipei

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # buster
          - BUILD_CONTEXT: buildbot/buster
            TARGET_PLATFORMS: linux/amd64
          # buster-android
          - BUILD_CONTEXT: buildbot/buster-android
            TARGET_PLATFORMS: linux/amd64
          # chisel
          - BUILD_CONTEXT: net/chisel
            TARGET_PLATFORMS: linux/amd64,linux/arm64
          # hev-socks5-server
          - BUILD_CONTEXT: net/hev-socks5-server
            TARGET_PLATFORMS: linux/amd64,linux/arm64
          # mtg
          - BUILD_CONTEXT: net/mtg
            TARGET_PLATFORMS: linux/amd64,linux/arm64
          # netspeeder
          - BUILD_CONTEXT: net/netspeeder
            TARGET_PLATFORMS: linux/amd64,linux/arm64
          # shadowsocks-libev
          - BUILD_CONTEXT: net/shadowsocks-libev
            TARGET_PLATFORMS: linux/amd64,linux/arm64
          # speedtest-go
          - BUILD_CONTEXT: utils/speedtest-go
            TARGET_PLATFORMS: linux/amd64,linux/arm64
          # vlmcsd
          - BUILD_CONTEXT: utils/vlmcsd
            TARGET_PLATFORMS: linux/amd64,linux/arm64
    steps:
      # prepare
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Append environment variables
        run: |
          echo "BUILD_TAG=$(basename ${{ matrix.BUILD_CONTEXT }})" >> $GITHUB_ENV

      # login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.BUILD_TAG }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.BUILD_TAG }}-buildx

      # build & push
      - name: Build image and Push to DockerHub
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          context: ${{ matrix.BUILD_CONTEXT }}
          tags: ${{ github.repository }}:${{ env.BUILD_TAG }}
          platforms: ${{ matrix.BUILD_PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
